# Run regularly to update dependencies and perform similar maintenance
maintain: 
    find . -name "*.ts" | xargs udd
    just --justfile core/design-system/lightning/Justfile maintain

# Run unit tests (docs/public, which are generated by tests, will be deleted first)
test:
    rm -rf docs/public && deno test -A --unstable --fail-fast