// this file is symlink'd by executive/publ/controller.ts:
//
// from executive/publ/console/public/server.js   (canonical)
//   to public/operational-context/server.auto.js (reference)
//
// it's imported as a module by all pages when they run in Console mode by
// pubctl.ts; it is run only by the browser, not at build time by Deno. If
// you make changes, you can easily just hit browser refresh to reload.

// the deps.auto.js file is generated by controller.ts and placed into
// public/operational-context/deps.auto.js when the server starts.
import * as d from "./deps.auto.js";

const rfOperationalCtx = {
    isExperimentalOperationalCtx: d.rfOperationalCtxArgs.isExperimentalOperationalCtx,
    publicUrlLocation: d.rfOperationalCtxArgs.publicUrlLocation,
    serviceBus: undefined,
    publicURL: function (path) { return d.rfOperationalCtxArgs.publicUrlLocation + path },
    diagnostics: {
        universal: {
            verbose: false,
            report: function () {
                console.info("%c[rfOperationalCtx]%c", "color:#D3D3D3", "color:#999999", ...arguments);
            }
        },
        fileImpact: {
            verbose: false,
            report: function () {
                console.info("%c[rfOperationalCtx fileImpact]%c", "color:#D3D3D3", "color:#999999", ...arguments);
            }
        },
        serviceBus: {
            verbose: false,
            report: function () {
                console.info("%c[rfOperationalCtx serviceBus]%c", "color:#D3D3D3", "color:#999999", ...arguments);
            }
        },
        workspaceTunnel: {
            verbose: false,
            report: function () {
                console.info("%c[rfOperationalCtx workspaceTunnel]%c", "color:#D3D3D3", "color:#777777", ...arguments);
            }
        },
    },
    console: {
        location: function (path) { return d.rfOperationalCtxArgs.publicUrlLocation + '/console' + path },
        tunnel: {
            sseHealthURL: d.rfOperationalCtxArgs.publicUrlLocation + '/console/sse/ping',
            sseURL: d.rfOperationalCtxArgs.publicUrlLocation + '/console/sse/tunnel',
            badgenRemoteBaseURL: d.rfOperationalCtxArgs.badgenRemoteBaseURL, // from env:RF_UNIVERSAL_BADGEN_REMOTE_BASE_URL
        }
    },
    workspace: {
        baseURL: "/workspace",
        footerContentDomID: "rf-universal-footer-experimental-server-workspace",
        isHotReloadAvailable: true,
        activePageTerminalRoute: undefined, // will be set in provision()
        reloadIfImpacted: (fsAbsPathAndFileNameImpacted, ctx) => {
            // rfOperationalCtx.workspace.activePageTerminalRoute should be set in rfOperationalCtx.provision()
            // to see if the "impacted" workspace file is our current page
            const activePageFileSysPath = rfOperationalCtx.workspace.activePageTerminalRoute?.fileSysPath;
            if (activePageFileSysPath == fsAbsPathAndFileNameImpacted) {
                location.reload();
            } else {
                const diags = rfOperationalCtx.diagnostics.fileImpact;
                if (diags.verbose) {
                    diags.report("rfOperationalCtx.workspace.reloadIfImpacted() called but this page was not impacted", fsAbsPathAndFileNameImpacted, rfOperationalCtx.workspace.activePageTerminalRoute, ctx);
                }
            }
        },
        tunnel: {
            sseHealthURL: d.rfOperationalCtxArgs.publicUrlLocation + '/workspace/sse/ping',
            sseURL: d.rfOperationalCtxArgs.publicUrlLocation + '/workspace/sse/tunnel',
            badgenRemoteBaseURL: d.rfOperationalCtxArgs.badgenRemoteBaseURL, // from env:RF_UNIVERSAL_BADGEN_REMOTE_BASE_URL
        },
        provision: function (clientLayout) {
            // this method will NOT be called before DOMContentLoaded so don't assume anything
            // we're not running in a server that supports experimental workspace (IDE)
            if (!window.rfOperationalCtx.isExperimentalOperationalCtx) return;

            const { diagnostics } = rfOperationalCtx;
            const reportServiceBusDiags = diagnostics.serviceBus.report;
            const reportWorkspaceTunnelDiags = diagnostics.workspaceTunnel.report;

            const wsTunnelStateBadge = d.badgenLiveBlock({
                // deno-lint-ignore require-await
                badgenBlockSupplier: async () => {
                    const block = d.badgenBlock();
                    block.init(); // async so don't depend on it, dependencies will be auto-loaded
                    return block;
                },
                badgeElementSupplier: () => document.getElementById("rf-universal-tunnel-state-summary-badge"),
                renderBadgeEventSupplier: () => ({ eventTarget: document, eventName: "render-rf-universal-tunnel-state-summary-badge-content" }),
                init: (block) => block,
            });
            wsTunnelStateBadge.init(); // async so don't depend on it yet, dependencies will be auto-loaded

            rfOperationalCtx.workspace.activePageTerminalRoute = clientLayout.route.terminal;
            if (diagnostics.universal.verbose) {
                diagnostics.universal.report("rfOperationalCtx workspace enabled for", clientLayout, rfOperationalCtx.workspace.activePageTerminalRoute);
            }

            let workspaceTunnel = undefined;
            const serviceBus = new d.ServiceBus(d.serviceBusArguments({
                fetchBaseURL: `/console/user-agent-bus`,
                esTunnels: function* (serviceBusOnMessage) {
                    const esURL = rfOperationalCtx.workspace.tunnel.sseURL;
                    const esPingURL = rfOperationalCtx.workspace.tunnel.sseHealthURL;
                    const eventSourceFactory = {
                        construct: (esURL) => {
                            // we have to prepare the entire EventSources
                            // each time we are called; this is because ESs
                            // can error out and be dropped/recreated
                            const result = new EventSource(esURL);
                            // ServiceBus only handles raw messages and does
                            // not do anything with listeners; this means
                            // typed events shouldn't be done by ES, it should
                            // be handled by ServiceBus (that's it's job!)
                            result.onmessage = serviceBusOnMessage;
                            return result;
                        }
                    };
                    workspaceTunnel = new d.EventSourceTunnel({
                        esURL, esPingURL, eventSourceFactory, options: {
                            onConnStateChange: (active, previous, tunnel) => {
                                const escn = d.eventSourceConnNarrative(tunnel);
                                if (diagnostics.workspaceTunnel.verbose) reportWorkspaceTunnelDiags("[provision!] connection state", escn.summary, escn.summaryHint, active, previous);
                                wsTunnelStateBadge.content({ label: "Tunnel", status: escn.summary, title: escn.summaryHint, color: escn.color }, true);
                            },
                            onReconnStateChange: (active, previous, reconnStrategy, tunnel) => {
                                const escn = d.eventSourceConnNarrative(tunnel, reconnStrategy);
                                if (diagnostics.workspaceTunnel.verbose) reportWorkspaceTunnelDiags("[provision!] reconnection state", active, previous, escn.summary, escn.summaryHint);
                                wsTunnelStateBadge.content({ label: "Tunnel", status: escn.summary, title: escn.summaryHint, color: escn.color }, true);
                            },
                        }
                    });
                    workspaceTunnel.init();
                    yield workspaceTunnel;
                }
            }));
            rfOperationalCtx.serviceBus = serviceBus;
            if (diagnostics.serviceBus.verbose) {
                serviceBus.observeFetchEvent((payload, reqInit) => reportServiceBusDiags("observed universal fetch", payload, reqInit));
                serviceBus.observeFetchEventResponse((respPayload, fetchPayload) => reportServiceBusDiags("observed universal fetchResponse", fetchPayload, respPayload));
                serviceBus.observeFetchEventError((error, reqInit, fetchPayload) => reportServiceBusDiags("observed universal fetchRespError", error, reqInit, fetchPayload));
                serviceBus.observeEventSource((esPayload) => reportServiceBusDiags("observed universal eventSource", esPayload));
            }

            const ping = d.pingService((baseURL) => baseURL);
            if (diagnostics.serviceBus.verbose) ping.observeEventSource(serviceBus, (payload) => reportServiceBusDiags("observed ping SSE", payload));
            const sfImpact = d.serverFileImpactService((baseURL) => baseURL);
            sfImpact.observeEventSource(serviceBus, (payload) => {
                if (diagnostics.serviceBus.verbose) reportServiceBusDiags("observed file impact SSE", payload);
                rfOperationalCtx.workspace.reloadIfImpacted(payload.serverFsAbsPathAndFileName);
            });

            const footerContentElem = document.getElementById(window.rfOperationalCtx.workspace.footerContentDomID);
            if (footerContentElem) {
                footerContentElem.style.display = 'block';
                const htmlDataSet = document.documentElement.dataset;
                if (htmlDataSet.rfOriginLayoutSrc) {
                    footerContentElem.innerHTML = `<p title="${htmlDataSet.rfOriginLayoutSrc}" class="localhost-diags">
                    Using layout <code class="localhost-diags-layout-origin">${htmlDataSet.rfOriginLayoutName}</code>
                    (<code class="localhost-diags-layout-origin">${htmlDataSet.rfOriginLayoutSymbol}</code>) in
                    <code class="localhost-diags-layout-origin-src">${htmlDataSet.rfOriginLayoutSrc.split('/').reverse()[0]}</code></p>`;
                } else {
                    footerContentElem.innerHTML = `<p title="${htmlDataSet.rfOriginLayoutSrc}" class="localhost-diags localhost-diags-warning">No layout information in <code>&lt;html data-rf-origin-layout-*&gt;</code></p>`;
                }
            }
        }
    },
}

window.addEventListener("clientLayout.provisionAfterContentLoaded", () => {
    rfOperationalCtx.workspace.provision(clientLayout);
}, false);

window.rfOperationalCtx = rfOperationalCtx;